AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ClusterName:
    Type: String
    Default: default
  FunctionName:
    Type: String
    Default: defaultFunc

Transform: AWS::Serverless-2016-10-31
Description: Example API
Resources:
  Func:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref FunctionName
      Handler: main
      CodeUri: ./func.d
      Runtime: provided
      Layers:
        - "arn:aws:lambda:us-west-2:332894900161:layer:lambda-layer-kubectl:1"
      MemorySize: 512
      Environment:
        Variables:
          cluster_name: !Ref ClusterName
      # Policies: 
      #   - AWSLambdaBasicExecutionRole
      Role: !Sub "arn:aws:iam::332894900161:role/LambdaEKSAdminRole"
      Timeout: 10


Outputs:
  LambdaFuncArn:
    Description: Lambda Func ARN
    Value: !GetAtt Func.Arn
    Export:
      Name: !Sub 'LambdaFuncArn-${AWS::StackName}'
  LambdaFuncName:
    Description: Lambda Func Name
    Value: !Ref Func
    Export:
      Name: !Sub 'LambdaFuncName-${AWS::StackName}'
  LambdaRoleArn:
    Description: Lambda Role ARN
    Value: !Sub "arn:aws:iam::332894900161:role/LambdaEKSAdminRole"
    Export:
      Name: !Sub 'LambdaRoleArn-${AWS::StackName}'
